# Build Docker image for this app using Azure Pipelines
# http://docs.microsoft.com/azure/devops/pipelines/languages/docker?view=vsts
pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  imageName: 'dotnetcore:$(Build.BuildId)'
  # define two more variables dockerId and dockerPassword in the build pipeline in UI

steps:
- script: |
    dotnet build --configuration $(buildConfiguration)
    #dotnet test dotnetcore-tests --configuration $(buildConfiguration) --logger trx
    find -wholename **/Just.Anarchy.Test*/*.csproj -print | xargs -i dotnet test {} --configuration $(buildConfiguration) --logger trx
    dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  env:
    pswd: $(dockerPassword)

# - task: DotNetCoreCLI@2
#   inputs:
#     command: test
#     projects: '**/Just.Anarchy.Test.*/*.csproj'
#     arguments: '--configuration $(buildConfiguration)'

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishBuildArtifacts@1
